version: "3.7"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    expose:
      - "5432"
    ports:
      - "5433:5432"
    volumes:
      - ./app/db/:/docker-entrypoint-initdb.d/

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - DB_SCHEMA=tanuki
      - DB_USER=tanuki
      - DB_PASSWORD=tanuki
      - DB_HOST=postgres
    depends_on:
      - postgres
    ports:
      - '3000:3000'
    volumes:
      - ./app:/app
