# Development version of docker-compose.yml
# Exposes ports and volumes to enable work on the container

version: "3.7"
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    expose:
      - "5432"
    ports:
      - "5433:5432"
    volumes:
      - ./app/db/:/docker-entrypoint-initdb.d/

  tailwind:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile.tailwind.dev
    stdin_open: true
    volumes:
      - ./app:/wrapper/app

  app:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile.dev
    depends_on:
      - postgres
      - tailwind
    ports:
      - '3000:3000'
    volumes:
      - ./app:/app
