version: "3.7"
services:
  postgres:
    image: postgres
    expose:
      - "5432"
    volumes:
      - ./app/db/:/docker-entrypoint-initdb.d/

  app:
    build:
      context: .
    depends_on:
      - postgres
    ports:
      - '3000:3000'
